[flake8]
# Set max-line-length to black compatible 88
max-line-length = 88
# Ignore flake8 warnings E203 and W503 that conflict with black formatting.
extend-ignore = E203, W503

[isort]
profile = black
